### ISSUE TITLE
Tensorflow and Keras installation

### ISSUE THREAD

**Issue by wehrad** [jouvetg/igm_old#1]
Hi Guillaume,

I was wondering why are Keras and Tensorflow installed with `pip` and not `conda`? ("Installing Python Packages" section of your README)

Installing with `pip` in a `conda` environment can lead to [complex issues](https://www.anaconda.com/blog/using-pip-in-a-conda-environment). And here, all the packages you install with `pip` are available with conda`.

**Comment by wehrad** [comment]
You could actually directly provide a `.yml` file for your environment before the installation of `cudatoolkit`, `cudnn` and `tensorflow-gpu` which could possibly be user specific.

Users would then only have to run `conda env create -f environment.yml`

**Comment by jouvetg** [comment]
Thanks Adrien, unfortunately, it seems that conda does not support yet tensorflow-gpu==2.4.0, that's why I keep using pip for now. I added an igm.yml.
